### ISSUE TITLE
精度页面论文目录

### ISSUE THREAD

**Issue by rn1024** [OpenRead-Academy/issue-report#1]
<img width="1910" alt="image" src="https://github.com/OpenRead-Academy/issue-report/assets/8408145/3392e07e-74e1-4932-8d0b-0353b9aa57b3">

**Describe the bug**
精度页面目录应该为组件内部滚动
https://www.openread.academy/paper/reading?id=2301.07597v1

**Comment by BensenHsu** [comment]
Fixed
