### ISSUE TITLE
Paper parsing error

### ISSUE THREAD

**Issue by zoewang177** [OpenRead-Academy/issue-report#10]
**Describe the bug**
Error showed up when parsing the paper

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1439" alt="image" src="https://github.com/OpenRead-Academy/issue-report/assets/82325326/5ea3156d-c481-481c-92a8-5b6421bd0ac5">

**Desktop (please complete the following information):**
OS: iOS
Browser: chrome
Version: 12.2

**Additional context**

**Comment by zoewang177** [comment]
[test 3.pdf](https://github.com/OpenRead-Academy/issue-report/files/12183770/test.3.pdf)

**Comment by BensenHsu** [comment]
Fixed.
