### ISSUE TITLE
首页第一屏的搜索框

### ISSUE THREAD

**Issue by rn1024** [OpenRead-Academy/issue-report#2]
<img width="1124" alt="image" src="https://github.com/OpenRead-Academy/issue-report/assets/8408145/391893cc-0b15-41e5-bd23-4ef7fc2c8bd3">
首页这里选中推荐文章后，建议可以直接跳转搜索，而不用用户再次点击回车
（界面上本身没有搜索的按钮）

**Comment by BensenHsu** [comment]
It is designed this way, no direct navigation.
