### ISSUE TITLE
PDF parsing error

### ISSUE THREAD

**Issue by Wang-hub-smart** [OpenRead-Academy/issue-report#3]
**Describe the bug**
The PDF parsing can't parse my paper correctly

**To Reproduce**

**Expected behavior**

**Screenshots**
![WechatIMG9507](https://github.com/OpenRead-Academy/issue-report/assets/82325326/3be221d3-576a-4374-a9f3-d5c850f9cd87)
[Automatic_Face_Recognition_of_Newborns_Infants_and_Toddlers_A_Longitudinal_Evaluation.pdf](https://github.com/OpenRead-Academy/issue-report/files/12159637/Automatic_Face_Recognition_of_Newborns_Infants_and_Toddlers_A_Longitudinal_Evaluation.pdf)

**Desktop (please complete the following information):**

**Additional context**

**Comment by Wang-hub-smart** [comment]
new bing

**Comment by BensenHsu** [comment]
Fixed, paper url: https://www.openread.academy/paper/extensive-read?id=or.7ceb4c00d188b61e971d61d11c3581cd.v1
