### ISSUE TITLE
PDF parsing no reaction

### ISSUE THREAD

**Issue by Wang-hub-smart** [OpenRead-Academy/issue-report#4]
**Describe the bug**
The pdf parsing didn't send me any response after uploading the pdf

**To Reproduce**

**Expected behavior**
An analyzed paper

**Screenshots**
![Xnip2023-07-25_19-57-23](https://github.com/OpenRead-Academy/issue-report/assets/82325326/2768d3ae-98df-4e84-ac17-6be8de2f8ffa)

**Desktop (please complete the following information):**
 - Browser: chrome

**Additional context**

**Comment by Wang-hub-smart** [comment]
[2304.01852.pdf](https://github.com/OpenRead-Academy/issue-report/files/12160863/2304.01852.pdf)

**Comment by BensenHsu** [comment]
It took 2 mins to finish parsing on my laptop:
<img width="1505" alt="image" src="https://github.com/OpenRead-Academy/issue-report/assets/51500098/917ce88e-0138-4c6b-8ecd-fd2c8e0153ba">

Please check your network, which is probably the cause for this issue.
