### ISSUE TITLE
or upload paper button no reaction

### ISSUE THREAD

**Issue by zoewang177** [OpenRead-Academy/issue-report#5]
**Describe the bug**
The "or upload paper button" doesn't have any reaction after clicking

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 12.5

**Additional context**

**Comment by BensenHsu** [comment]
Not an issue on my end.

**Comment by zoewang177** [comment]
Still no reaction on my side.
