### ISSUE TITLE
PDF parsing error

### ISSUE THREAD

**Issue by Wang-hub-smart** [OpenRead-Academy/issue-report#6]
**Describe the bug**

**To Reproduce**
1. Go to 'trending'
2. Click on 'read' of one paper
3. See error

**Expected behavior**
see the analyzed paper

**Screenshots**
<img width="1428" alt="image" src="https://github.com/OpenRead-Academy/issue-report/assets/82325326/8aead485-d7b2-49de-928f-f72267ecc5e0">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 12.2

**Additional context**

**Comment by BensenHsu** [comment]
This was caused by our server storage limitation, it's fixed.
