### ISSUE TITLE
Sign in hyperlink under Paper Espresso

### ISSUE THREAD

**Issue by Wang-hub-smart** [OpenRead-Academy/issue-report#7]
**Is your feature request related to a problem? Please describe.**
I don't want to hover over the nav bar and sign in from the nav bar.

**Describe the solution you'd like**
I want a hyperlink for the "sign in" so I can sign in immediately without waiting for the nav bar to pop up.

**Describe alternatives you've considered**
nope

**Additional context**
<img width="1430" alt="image" src="https://github.com/OpenRead-Academy/issue-report/assets/82325326/2719bf64-9828-44a8-b532-623f0f39545e">

**Comment by BensenHsu** [comment]
Added
