### ISSUE TITLE
No paper espresso

### ISSUE THREAD

**Issue by zoewang177** [OpenRead-Academy/issue-report#8]
**Describe the bug**
There's no paper espresso result for the paper

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1552" alt="image" src="https://github.com/OpenRead-Academy/issue-report/assets/82325326/d9f64935-47c0-4668-a081-9cc16da0fc32">

**Desktop (please complete the following information):**
OS: iOS
Browser: chrome
Version: 12.2

**Additional context**

**Comment by BensenHsu** [comment]
Fixed
